# Generated by Django 2.0.3 on 2018-04-11 01:39

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=30.0, help_text='Fee, dollars per ton of CO2.', validators=[calc.models.validate_nonnegative])),
                ('rebate_portion', models.FloatField(default=0.7, help_text='Portion of total revenue. The rest goes to sustainableinvestment and relief for vulnerable businesses and communities.', validators=[calc.models.validate_0to1])),
                ('period', models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year')], default='month', help_text='Time range for calculation.', max_length=5)),
                ('adults', models.PositiveIntegerField(default=1, help_text='Members of household 18 and older.', validators=[calc.models.validate_leq20])),
                ('children', models.PositiveIntegerField(default=0, help_text='Members of household under 18.', validators=[calc.models.validate_leq20])),
                ('gasoline_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('gasoline_type', models.CharField(choices=[('e10', '10% Ethanol'), ('e0', 'Pure Gasoline'), ('diesel', 'Diesel'), ('b20', '20% Biodiesel')], default='e10', max_length=40)),
                ('gasoline_unit', models.CharField(choices=[('gallon', 'gallons')], default=('gallon', 'gallons'), max_length=40)),
                ('elec_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('elec_type', models.CharField(choices=[('pseg', 'PSE&G'), ('rockland', 'Orange Rockland Electric'), ('jcpl', 'Jersey Central Power & Light'), ('atlantic', 'Atlantic City Electric')], default='pseg', help_text='Your electric utility provider.', max_length=40)),
                ('elec_unit', models.CharField(choices=[('kWh', 'kWh')], default=('kWh', 'kWh'), max_length=40)),
                ('heating_amt', models.FloatField(default=1.0, validators=[calc.models.validate_nonnegative])),
                ('heating_type', models.CharField(choices=[('gas', 'Natural Gas'), ('fuel', 'Fuel Oil'), ('elec', 'Electricity')], default='gas', max_length=40)),
                ('heating_unit', models.CharField(choices=[('therm', 'therms'), ('gallon', 'gallons'), ('kWh', 'kWh')], default=('therm', 'therms'), max_length=40)),
            ],
        ),
    ]
