# Generated by Django 2.0.2 on 2018-04-20 00:37

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20180413_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='elec_amt',
            field=models.FloatField(default=9000.0, validators=[calc.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gasoline_amt',
            field=models.FloatField(default=70.0, validators=[calc.models.validate_nonnegative]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heating_amt',
            field=models.FloatField(default=164.0, validators=[calc.models.validate_nonnegative]),
        ),
    ]
