# Generated by Django 2.0.3 on 2018-04-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20180420_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='heating_type',
            field=models.CharField(choices=[('gas', 'Natural Gas'), ('fuel', 'Fuel Oil')], default='gas', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='heating_unit',
            field=models.CharField(choices=[('therm', 'therms'), ('gallon', 'gallons')], default=('therm', 'therms'), max_length=40),
        ),
    ]
