# Generated by Django 2.0.3 on 2018-05-11 02:33

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20180421_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='elec_amt',
            field=models.FloatField(default=900.0, validators=[calc.models.validate_nonnegative]),
        ),
    ]
